rct/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from rct.forms import NewPasswordForm

app_name='rct'
urlpatterns = [
    #PUBLIC
    path('',views.index,name='index'),
    path('recetas',views.recetas,name='recetas'),
    path('mis_recetas_creadas/',views.mis_recetas_creadas,name='mis_recetas'),
    path('mis_recetas_guardadas/',views.mis_recetas_guardadas,name='favoritos'),
    path('mis_recetas/crear_receta',views.crear_receta,name='crear_receta'),
    path('mis_recetas/editar_receta/<int:id>/',views.editar_receta,name='editar'),
    path('mis_recetas/eliminar_receta/<int:id>/',views.eliminar_receta,name='eliminar'),
    path('mis_recetas/crear_receta/crear_producto',views.crear_producto,name='crear_producto'),
    path('mis_recetas/crear_receta/crear_medida',views.crear_medida,name='crear_medida'),
    path('receta/<int:id>/',views.receta,name='receta'),
    path('receta/<int:id>/publica',views.receta_publica,name='receta_publica'),
    path('receta/<int:id>/privada',views.receta_privada,name='receta_privada'),
    path('receta/<int:parent_id>/editar_ingrediente/<int:id>/',views.editar_ingrediente,name='editar_ingrediente'),
    path('receta/<int:parent_id>/eliminar_ingrediente/<int:id>/',views.eliminar_ingrediente,name='eliminar_ingrediente'),
    path('receta/<int:parent_id>/guardar_receta/',views.guardar_receta,name='guardar_receta'),
    path('receta/<int:parent_id>/borrar_receta/<int:id>/',views.borrar_receta,name='borrar_receta'),
    path('registro',views.registro,name='registro'),
    path('login',views.recetas_login,name='login'),
    path('password_change',views.cambio_contraseña,name='password_change'),
    path('reset_password',views.password_reset_request,name='reset_password'),
    path('reset_password_sent',auth_views.PasswordResetDoneView.as_view(template_name='rct/public/password_reset_sent.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(form_class=NewPasswordForm,template_name='rct/public/password_reset_form.html',success_url=reverse_lazy('rct:password_reset_complete')),name='password_reset_confirm'),
    path('reset_password_complete',auth_views.PasswordResetDoneView.as_view(template_name='rct/public/password_reset_done.html'),name='password_reset_complete'),
    path('logout',auth_views.LogoutView.as_view(template_name='rct/public/index.html'),name='logout'),
    path('contact',views.contact,name='contact'),
    #ADMINISTRACION
    path('administracion',views.index_administracion,name='administracion'),
    path('administracion/perfil/<int:id>/',views.profile_administracion,name='perfil_admin'),
    path('administracion/perfil/<int:id>/editar-perfil',views.edit_profile_administracion,name='editar_perfil_admin'),
    path('administracion/mensajes',views.mensajes_admin,name='mensajes'),
    path('administracion/mensajes/<int:id>',views.mensaje_admin,name='mensaje'),
    path('administracion/mensajes/crear-mensaje',views.crear_mensaje_admin,name='crear_mensaje'),
    path('administracion/mensajes/<int:id>/eliminar-mensaje',views.eliminar_mensaje,name='eliminar_mensaje'),
    path('administracion/mensajes/<int:id>/mensaje-no-leido',views.mensaje_no_leido,name='mensaje_no_leido'),
    path('administracion/usuarios',views.usuarios,name='usuarios'),
    path('administracion/usuarios/<int:id>/editar-usuario/',views.editar_usuarios_admin,name='editar_usuario'),
    path('administracion/usuarios/<int:id>/eliminar-usuario/',views.eliminar_usuarios_admin,name='eliminar_usuario'),
    path('administracion/staff',views.staff,name='staff'),
    path('administracion/recetas',views.recetas_admin,name='recetas_admin'),
    path('administracion/recetas/<int:id>/instrucciones',views.pasos_receta_admin,name='instrucciones_admin'),
    path('administracion/recetas/<int:id>/instrucciones/editar/',views.editar_pasos_receta_admin,name='editar_instrucciones_admin'),
    path('administracion/recetas/crear-receta',views.crear_recetas_admin,name='crear_receta_admin'),
    path('administracion/recetas/editar-receta/<int:id>/',views.editar_recetas_admin,name='editar_receta_admin'),
    path('administracion/recetas/eliminar-receta/<int:id>/',views.eliminar_recetas_admin,name='eliminar_receta_admin'),
    path('administracion/recetas/<int:parent_id>/ingredientes',views.ingredientes_receta_admin,name='ingredientes_receta_admin'),
    path('administracion/recetas/<int:parent_id>/ingredientes/agregar-ingrediente',views.crear_ingredientes_receta_admin,name='agregar_ingrediente_receta'),
    path('administracion/recetas/<int:parent_id>/ingredientes/editar-ingrediente/<int:id>/',views.editar_ingredientes_receta_admin,name='editar_ingrediente_receta'),
    path('administracion/recetas/<int:parent_id>/ingredientes/eliminar-ingrediente/<int:id>/',views.eliminar_ingredientes_receta_admin,name='eliminar_ingrediente_receta'),
    path('administracion/ingredientes',views.ingredientes_admin,name='ingredientes_admin'),
    path('administracion/productos',views.productos_admin,name='productos_admin'),
    path('administracion/productos/crear-producto',views.crear_productos_admin,name='crear_prod_admin'),
    path('administracion/productos/editar-producto/<int:id>/',views.editar_productos_admin,name='editar_prod_admin'),
    path('administracion/productos/eliminar-producto/<int:id>/',views.eliminar_productos_admin,name='eliminar_prod_admin'),
    path('administracion/unidades-medida',views.medidas_admin,name='medidas_admin'),
    path('administracion/unidades-medida/crear-medida',views.crear_medidas_admin,name='crear_med_admin'),
    path('administracion/unidades-medida/editar-medida/<int:id>/',views.editar_medidas_admin,name='editar_med_admin'),
    path('administracion/unidades-medida/eliminar-medida/<int:id>/',views.eliminar_medidas_admin,name='eliminar_med_admin'),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

recetario/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('rctadmin/', admin.site.urls),
    # urls api
    path('rct_api/',include('api_rct.urls')),
    # urls rct (app)
    path('',include('rct.urls')),
]

rct/views.py
from django.shortcuts import render,redirect,get_object_or_404
from rct.forms import *
from django.contrib import messages
from rct.models import *
from django.contrib.auth import authenticate,login
from django.contrib.auth.decorators import login_required
from django.forms.models import modelformset_factory # model form for querysets
from django.core.mail import send_mail,BadHeaderError
from django.conf import settings
from django.db import IntegrityError
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.db.models import Count

# Create your views here.

#PUBLIC
def index(request):
    return render(request,'rct/public/index.html',)

# Content views (Retrieve)
def recetas(request):
    recetas = Recetas.objects.filter(public=True)
    archivo = None
    if  request.user.is_authenticated:
        archivo = RecetasGuardadas.objects.filter(fkuser=request.user)
    return render(request,'rct/public/recetas.html',{'recetas':recetas,'archivo':archivo})

@login_required(login_url=settings.LOGIN_URL)
def mis_recetas_creadas(request):
    recetas = Recetas.objects.filter(fkuser=request.user)
    return render(request,'rct/public/mis_recetas_creadas.html',{'recetas':recetas})

@login_required(login_url=settings.LOGIN_URL)
def mis_recetas_guardadas(request):
    archivo = RecetasGuardadas.objects.filter(fkuser=request.user)
    return render(request,'rct/public/mis_recetas_guardadas.html',{'archivo':archivo})

def receta(request,id=None):
    receta = get_object_or_404(Recetas,id=id)
    ingredientes = Ingredientes.objects.filter(fkrecetas=id)
    archivo = None
    if  request.user.is_authenticated:
        try:
            archivo = RecetasGuardadas.objects.get(receta_guardada=id,fkuser=request.user)
        except RecetasGuardadas.DoesNotExist:
            archivo = None
    return render(request,'rct/public/receta.html',{'receta':receta,'ingredientes':ingredientes,'archivo':archivo})

def contact(request):
    if request.method == 'POST':
        contacto_form = ContactoForm(request.POST or None)
        if contacto_form.is_valid():
            email=contacto_form.cleaned_data['email']
            asunto=contacto_form.cleaned_data['asunto']
            nombre=contacto_form.cleaned_data['nombre']
            mensaje=contacto_form.cleaned_data['mensaje']
            data={
                'email': email,
                'asunto': asunto,
                'nombre': nombre,
                'mensaje': mensaje,
            }
            message='''
            De: {}

            Nombre: {}

            Mensaje: {}
            '''.format(data['email'],data['nombre'],data['mensaje'])
            send_mail(data['asunto'],message,'calde_kpo@hotmail.com',['calde_kpo@hotmail.com'],fail_silently=False)
            messages.success(request,'¡Gracias por comunicarte con nostros, te estaremos respondiedo a la brevedad!')
            contacto_form = ContactoForm()
            return redirect('rct:contact')
    else:
        contacto_form = ContactoForm()
    return render(request,'rct/public/contact.html',{'contacto_form':contacto_form})

# login
def registro(request):
    if request.method == 'POST':
        register_form = RegisterForm(request.POST or None)
        if register_form.is_valid():
            register_form.save()
            messages.success(request, f'Tu cuenta fue creada con exito!')
            return redirect('rct:login')
    else:
        register_form = RegisterForm()
    return render(request,'rct/public/registro.html',{'register_form':register_form})

def recetas_login(request):
    if request.method == 'POST':
        username= request.POST['username']
        password= request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            form = login(request, user)
            nxt = request.GET.get('next',None)
            if nxt is None:
                return redirect('rct:index')
            else:
                return redirect(nxt)
        else:
            messages.error(request,'El usuario o la contraseña no son validos')
    form = Logueo()
    return render(request,'rct/public/login.html',{'form':form})

@login_required(login_url=settings.LOGIN_URL)
def cambio_contraseña(request):
    if request.method == 'POST':
        form = PassChangeForm(user=request.user, data=request.POST or None)
        if form.is_valid():
            chng = form.save(commit=False)
            chng.user = request.user
            chng.save()
            messages.success(request, f'Tu Contraseña fue cambiada con exito!')
            return redirect('rct:login')
    else:
        form = PassChangeForm(user=request.user)
    return render(request,'rct/public/password_change.html',{'form':form})

def password_reset_request(request):
    if request.method == 'POST':
        form = PassResetForm(request.POST or None)
        if form.is_valid():
            data = form.cleaned_data['email']
            user_email = User.objects.filter(Q(email=data))
            if user_email.exists():
                for user in user_email:
                    subject = 'Reseteo de contraseña'
                    email_template = 'rct/public/password_message.txt'
                    parameters = {
                        'email': user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'recetArio',
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                        'user': user.username,
                    }
                    email = render_to_string(email_template,parameters)
                    try:
                        send_mail(subject,email,'calde_kpo@hotmail.com',[user.email],fail_silently=False)
                    except:
                        return HttpResponse('Invalid Header')
                    return redirect('rct:password_reset_done')
    else:
        form = PassResetForm()
    return render(request,'rct/public/password_reset.html',{'form':form})

# CUD
@login_required(login_url=settings.LOGIN_URL)
def crear_receta(request):
    IngredientesFormset = modelformset_factory(Ingredientes, form=IngredientesForm, fields=['fkproductos','cantidad','fkunidad_medida'], extra=0)
    qs = Ingredientes.objects.filter(fkrecetas=None)
    if request.method=='POST':
        formulario = RecetasForm(request.POST or None,request.FILES or None)
        formset = IngredientesFormset(request.POST or None)
        if all([formulario.is_valid(), formset.is_valid()]):
            form=formulario.save(commit=False)
            form.fkuser=request.user
            form.save()
            try:
                for field in formset:
                    forms = field.save(commit=False)
                    forms.fkrecetas = form
                    forms.save()
                return redirect('rct:mis_recetas')
            except IntegrityError:
                messages.error(request,'El ingrediente no puede estar vacio, completalo o eliminalo para guardar.')
                return render(request,'rct/public/crear_receta.html',{'formulario':formulario,'formset':formset}) 
    else:
        formulario = RecetasForm()
        formset = IngredientesFormset(queryset=qs)
    return render(request,'rct/public/crear_receta.html',{'formulario':formulario,'formset':formset})

@login_required(login_url=settings.LOGIN_URL)
def editar_receta(request,id=None):
    obj = get_object_or_404(Recetas, id=id)
    IngredientesFormset = modelformset_factory(Ingredientes,form=IngredientesForm,fields=['fkproductos','cantidad','fkunidad_medida'],extra=0)
    qs = obj.ingredientes_set.all()
    if request.method=='POST':
        formulario = RecetasForm(request.POST or None,request.FILES or None,instance=obj)
        formset = IngredientesFormset(request.POST or None,queryset=qs)
        if all([formulario.is_valid(), formset.is_valid()]):
            form = formulario.save(commit=False)
            form.save()
            try:
                for field in formset:
                    forms = field.save(commit=False)
                    forms.fkrecetas = form
                    forms.save()
                return redirect('rct:mis_recetas')
            except IntegrityError:
                messages.error(request,'El ingrediente no puede estar vacio, completalo o eliminalo para guardar.')
                return render(request,'rct/public/editar_receta.html',{'receta':obj,'formulario':formulario,'formset':formset})
    else:
        formulario = RecetasForm(instance=obj)
        formset = IngredientesFormset(queryset=qs)
    return render(request,'rct/public/editar_receta.html',{'receta':obj,'formulario':formulario,'formset':formset})

@login_required(login_url=settings.LOGIN_URL)
def editar_ingrediente(request,parent_id=None,id=None):
    ingrediente = get_object_or_404(Ingredientes,fkrecetas=parent_id,id=id)
    if request.method == 'POST':
        formulario = IngredientesForm(request.POST or None, instance=ingrediente)
        if formulario.is_valid():
            formulario.save()
            success_url = reverse('rct:receta', kwargs={'id':parent_id})
            return redirect(success_url)
    else:
        formulario = IngredientesForm(instance=ingrediente)
    return render(request,'rct/public/editar_ingrediente.html',{'formulario':formulario})

@login_required(login_url=settings.LOGIN_URL)
def eliminar_receta(request,id=None):
    try:
        receta = Recetas.objects.get(id=id)
    except Recetas.DoesNotExist:
        return render(request,'rct/public/404.html')
    receta.delete() 
    return redirect('rct:mis_recetas')

templates/rct/administration/crear_ing_rec.html
{% extends './base_administracion.html' %}
{% block content %}
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Agregar Ingrediente</h1>
    </div>

    <div class="row">
        <div class="col-lg-6">
            <!-- Basic Card Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Receta: {{ receta.nombre_receta }}</h6>
                </div>
                <div class="card-body">
                    {% include './form1.html' %}
                        <a href="{% url 'rct:ingredientes_receta_admin' receta.id %}"><input class="btn btn-warning" type="button" value="Cancel"></a>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock content %}

templates/rct/administration/editar_medida_admin.html
{% extends './base_administracion.html' %}
{% block content %}
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Editar Medida</h1>
    </div>

    <div class="row">
        <div class="col-lg-6">
            <!-- Basic Card Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Medida</h6>
                </div>
                <div class="card-body">
                    {% include './form1.html' %}
                        <a href="{% url 'rct:medidas_admin' %}"><input class="btn btn-warning" type="button" value="Cancel"></a>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock content %}

templates/rct/administration/editar_usuario.html
{% extends './base_administracion.html' %}
{% block content %}
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Editar Usuario</h1>
    </div>

    <div class="row">
        <div class="col-lg-6">
            <!-- Basic Card Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">usuario: {{ usuario.first_name }}</h6>
                </div>
                <div class="card-body">
                    {% include './form1.html' %}
                        <a href="{% url 'rct:usuarios' %}"><input class="btn btn-warning" type="button" value="Cancel"></a>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock content %}

templates/rct/administration/ingredientes_receta.html
{% extends './base_administracion.html' %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-2 text-gray-800">Ingredientes</h1>
        <a href="{% url 'rct:agregar_ingrediente_receta' receta.id %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fa-solid fa-plus"></i> Agregar Ingrediente</a>
    </div>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Receta: {{ receta.nombre_receta }}</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Producto</th>
                            <th>Cantidad</th>
                            <th>Unidad de Medida</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Id</th>
                            <th>Producto</th>
                            <th>Cantidad</th>
                            <th>Unidad de Medida</th>
                            <th>Acciones</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for ingrediente in ingredientes %}
                            <tr>
                                <td>{{ ingrediente.id }}</td>
                                <td>{{ ingrediente.fkproductos }}</td>
                                <td>{{ ingrediente.cantidad }}</td>
                                <td>{{ ingrediente.fkunidad_medida }}</td>
                                <td>
                                    <a href="{% url 'rct:editar_ingrediente_receta' receta.id ingrediente.id%}" title="Editar" class="btn-circle btn-warning btn-sm"><i class="fas fa-pencil"></i></a>
                                    <a href="{% url 'rct:eliminar_ingrediente_receta' receta.id ingrediente.id%}" title="Eliminar" class="btn-circle btn-danger btn-sm"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
{% endblock content %}

templates/rct/administration/instrucciones.html
{% extends './base_administracion.html' %}
{% block content %}
<h1 class="h3 mb-2 text-gray-800">Instrucciones</h1>
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div
        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Receta: {{ receta.nombre_receta }}</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item" href="{% url 'rct:editar_instrucciones_admin' receta.id %}">Editar</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'rct:recetas_admin' %}">Volver</a>
            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {{ receta.pasos_receta }}
    </div>
</div>
{% endblock content %}

templates/rct/administration/mensaje.html
{% extends './base_administracion.html' %}
{% block content %}
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-2 text-gray-800">Mensaje</h1>
    </div>
    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div
            class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Asunto: {{ mensaje.subject }}</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                    aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Acciones:</div>
                    <a class="dropdown-item" href="{% url 'rct:crear_mensaje' %}">Responder</a>
                    <a class="dropdown-item" href="{% url 'rct:mensaje_no_leido' mensaje.id %}">Marcar como NO leido</a>
                    <a class="dropdown-item" href="{% url 'rct:eliminar_mensaje' mensaje.id %}">Eliminar</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'rct:mensajes' %}">Volver</a>
                </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            <p>Remitente: {{ mensaje.sender }}</p>
            <p>Fecha de envío: {{ mensaje.created_at }}</p>
            <div class="dropdown-divider"></div>
            <p>Mensaje:</p>
            <p>{{ mensaje.msg_content }}</p>
        </div>
    </div>
</div>
{% endblock content %}

templates/rct/administration/mensajes.html
{% extends './base_administracion.html' %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-2 text-gray-800">Central de Mensajes</h1>
        <a href="{% url 'rct:crear_mensaje' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fa-solid fa-plus"></i> Crear Mensaje</a>
    </div>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Inbox</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Fecha</th>
                            <th>Asunto</th>
                            <th>Sender</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Fecha</th>
                            <th>Asunto</th>
                            <th>Sender</th>
                            <th>Acciones</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for mensaje in listado %}
                            <tr>
                                <td>{{ mensaje.created_at|date:"d-m-y | h:i:s" }}</td>
                                <td>{{ mensaje.subject }}</td>
                                <td>{{ mensaje.sender }}</td>
                                <td>
                                    {% if mensaje.read == False %}<a href="{% url 'rct:mensaje' mensaje.id %}" title="No Leido" class="btn-circle btn-primary btn-sm"><i class="fas fa-envelope"></i></a>{% endif %}
                                    {% if mensaje.read == True %}<a href="{% url 'rct:mensaje' mensaje.id %}" title="Leido" class="btn-circle btn-primary btn-sm"><i class="fas fa-envelope-open"></i></a>{% endif %}
                                    <a href="{% url 'rct:eliminar_mensaje' mensaje.id %}" title="Eliminar" class="btn-circle btn-secondary btn-sm"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
{% endblock content %}

templates/rct/administration/productos_admin.html
{% extends './base_administracion.html' %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-2 text-gray-800">Productos</h1>
        <a href="{% url 'rct:crear_prod_admin' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fa-solid fa-plus"></i> Crear Producto</a>
    </div>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Listado</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Producto</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Id</th>
                            <th>Producto</th>
                            <th>Acciones</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for producto in productos %}
                            <tr>
                                <td>{{ producto.id }}</td>
                                <td>{{ producto.nombre_producto }}</td>
                                <td>
                                    <a href="{% url 'rct:editar_prod_admin' producto.id %}" title="Editar" class="btn-circle btn-warning btn-sm"><i class="fas fa-pencil"></i></a>
                                    <a href="{% url 'rct:eliminar_prod_admin' producto.id %}" title="Eliminar" class="btn-circle btn-danger btn-sm"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
{% endblock content %}